# Generated by Django 4.1.1 on 2023-05-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nameFirst',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
