# Generated by Django 4.1.1 on 2023-05-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0002_user_namefirst'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nameLast',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
