# Generated by Django 4.1.1 on 2023-05-07 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaccimo', '0003_user_namelast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='vaccination_site',
            new_name='firstDose',
        ),
        migrations.AddField(
            model_name='user',
            name='secondDose',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='sideeffect2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('muscle_ache', models.CharField(default='No', max_length=100)),
                ('headache', models.CharField(default='No', max_length=100)),
                ('fever', models.CharField(default='No', max_length=100)),
                ('redness', models.CharField(default='No', max_length=100)),
                ('swelling', models.CharField(default='No', max_length=100)),
                ('chills', models.CharField(default='No', max_length=100)),
                ('join_pain', models.CharField(default='No', max_length=100)),
                ('fatigue', models.CharField(default='No', max_length=100)),
                ('nausea', models.CharField(default='No', max_length=100)),
                ('vomiting', models.CharField(default='No', max_length=100)),
                ('feverish', models.CharField(default='No', max_length=100)),
                ('warmth', models.DateField(auto_now=True)),
                ('induration', models.CharField(default='No', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('itch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccimo.questioner')),
                ('tenderness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccimo.user')),
            ],
            options={
                'db_table': 'sideeffect2',
            },
        ),
    ]
