# Generated by Django 4.1.1 on 2023-05-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0004_rename_vaccination_site_user_firstdose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateVaccinated',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vaccination_brand2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
