# Generated by Django 4.1.1 on 2023-05-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0006_remove_sideeffect2_itch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstBooster',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secondBooster',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
