# Generated by Django 4.1.1 on 2023-05-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0009_seconddose_secondbooster_firstbooster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bday',
            new_name='dateVaccinated1',
        ),
        migrations.AddField(
            model_name='user',
            name='dateVaccinated2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dateVaccinated3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vaccination_brand1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vaccination_brand3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
