# Generated by Django 4.1.1 on 2023-05-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0010_rename_bday_user_datevaccinated1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstbooster',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='firstdose',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='secondbooster',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seconddose',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='firstbooster',
            name='chestPain',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='firstdose',
            name='chestPain',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='secondbooster',
            name='chestPain',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='seconddose',
            name='chestPain',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterModelTable(
            name='firstbooster',
            table='firstbooster',
        ),
        migrations.AlterModelTable(
            name='firstdose',
            table='firstdose',
        ),
        migrations.AlterModelTable(
            name='secondbooster',
            table='secondbooster',
        ),
        migrations.AlterModelTable(
            name='seconddose',
            table='seconddose',
        ),
    ]
