# Generated by Django 4.1.1 on 2023-05-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0011_firstbooster_date_firstdose_date_secondbooster_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
