# Generated by Django 4.1.1 on 2023-05-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0012_alter_user_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstbooster',
            name='others',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='firstdose',
            name='others',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='secondbooster',
            name='others',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seconddose',
            name='others',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
