# Generated by Django 4.1.1 on 2023-05-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0013_alter_firstbooster_others_alter_firstdose_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suffix',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
