# Generated by Django 4.1.1 on 2023-05-09 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vaccimo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaccimo', '0014_user_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='suffix',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.CreateModel(
            name='userRestorData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(blank=True, null=True, upload_to=vaccimo.models.filepath)),
                ('email', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('suffix', models.CharField(default='N/A', max_length=100)),
                ('nameFirst', models.CharField(max_length=100, null=True)),
                ('nameLast', models.CharField(max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=100, null=True)),
                ('firstDose', models.CharField(max_length=100, null=True)),
                ('secondDose', models.CharField(max_length=100, null=True)),
                ('firstBooster', models.CharField(max_length=100, null=True)),
                ('secondBooster', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('age', models.CharField(max_length=100, null=True)),
                ('dateVaccinated', models.CharField(max_length=100, null=True)),
                ('dateVaccinated1', models.CharField(max_length=100, null=True)),
                ('dateVaccinated2', models.CharField(max_length=100, null=True)),
                ('dateVaccinated3', models.CharField(max_length=100, null=True)),
                ('vaccination_brand', models.CharField(max_length=100, null=True)),
                ('vaccination_brand1', models.CharField(max_length=100, null=True)),
                ('vaccination_brand2', models.CharField(max_length=100, null=True)),
                ('vaccination_brand3', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userRestorData',
            },
        ),
    ]
