# Generated by Django 4.1.1 on 2023-05-09 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaccimo', '0015_alter_user_suffix_userrestordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='seconddoserestore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='0', max_length=100)),
                ('InjectionSitePain', models.CharField(default='No', max_length=100)),
                ('headache', models.CharField(default='No', max_length=100)),
                ('fever', models.CharField(default='No', max_length=100)),
                ('rashes', models.CharField(default='No', max_length=100)),
                ('itchiness', models.CharField(default='No', max_length=100)),
                ('cough', models.CharField(default='No', max_length=100)),
                ('bodyPain', models.CharField(default='No', max_length=100)),
                ('soarThroat', models.CharField(default='No', max_length=100)),
                ('stomachAche', models.CharField(default='No', max_length=100)),
                ('vomiting', models.CharField(default='No', max_length=100)),
                ('difficultyOfBreathing', models.CharField(default='No', max_length=100)),
                ('chestPain', models.CharField(default='No', max_length=100)),
                ('disorentation', models.CharField(default='No', max_length=100)),
                ('tunnelVision', models.CharField(default='No', max_length=100)),
                ('seizure', models.CharField(default='No', max_length=100)),
                ('others', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seconddoserestore',
            },
        ),
        migrations.CreateModel(
            name='secondboosterrestored',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='0', max_length=100)),
                ('InjectionSitePain', models.CharField(default='No', max_length=100)),
                ('headache', models.CharField(default='No', max_length=100)),
                ('fever', models.CharField(default='No', max_length=100)),
                ('rashes', models.CharField(default='No', max_length=100)),
                ('itchiness', models.CharField(default='No', max_length=100)),
                ('cough', models.CharField(default='No', max_length=100)),
                ('bodyPain', models.CharField(default='No', max_length=100)),
                ('soarThroat', models.CharField(default='No', max_length=100)),
                ('stomachAche', models.CharField(default='No', max_length=100)),
                ('vomiting', models.CharField(default='No', max_length=100)),
                ('difficultyOfBreathing', models.CharField(default='No', max_length=100)),
                ('chestPain', models.CharField(default='No', max_length=100)),
                ('disorentation', models.CharField(default='No', max_length=100)),
                ('tunnelVision', models.CharField(default='No', max_length=100)),
                ('seizure', models.CharField(default='No', max_length=100)),
                ('others', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'secondboosterrestored',
            },
        ),
        migrations.CreateModel(
            name='firstdoserestore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='0', max_length=100)),
                ('InjectionSitePain', models.CharField(default='No', max_length=100)),
                ('headache', models.CharField(default='No', max_length=100)),
                ('fever', models.CharField(default='No', max_length=100)),
                ('rashes', models.CharField(default='No', max_length=100)),
                ('itchiness', models.CharField(default='No', max_length=100)),
                ('cough', models.CharField(default='No', max_length=100)),
                ('bodyPain', models.CharField(default='No', max_length=100)),
                ('soarThroat', models.CharField(default='No', max_length=100)),
                ('stomachAche', models.CharField(default='No', max_length=100)),
                ('vomiting', models.CharField(default='No', max_length=100)),
                ('difficultyOfBreathing', models.CharField(default='No', max_length=100)),
                ('chestPain', models.CharField(default='No', max_length=100)),
                ('disorentation', models.CharField(default='No', max_length=100)),
                ('tunnelVision', models.CharField(default='No', max_length=100)),
                ('seizure', models.CharField(default='No', max_length=100)),
                ('others', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'firstdoserestore',
            },
        ),
        migrations.CreateModel(
            name='firstboosterrestore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='0', max_length=100)),
                ('InjectionSitePain', models.CharField(default='No', max_length=100)),
                ('headache', models.CharField(default='No', max_length=100)),
                ('fever', models.CharField(default='No', max_length=100)),
                ('rashes', models.CharField(default='No', max_length=100)),
                ('itchiness', models.CharField(default='No', max_length=100)),
                ('cough', models.CharField(default='No', max_length=100)),
                ('bodyPain', models.CharField(default='No', max_length=100)),
                ('soarThroat', models.CharField(default='No', max_length=100)),
                ('stomachAche', models.CharField(default='No', max_length=100)),
                ('vomiting', models.CharField(default='No', max_length=100)),
                ('difficultyOfBreathing', models.CharField(default='No', max_length=100)),
                ('chestPain', models.CharField(default='No', max_length=100)),
                ('disorentation', models.CharField(default='No', max_length=100)),
                ('tunnelVision', models.CharField(default='No', max_length=100)),
                ('seizure', models.CharField(default='No', max_length=100)),
                ('others', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'firstboosterrestore',
            },
        ),
    ]
